"""add author rating review

Revision ID: 560685b3ea68
Revises: ed5463cf11ff
Create Date: 2026-06-08 08:23:57.293292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560685b3ea68'
down_revision: Union[str, Sequence[str], None] = 'ed5463cf11ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_read', sa.Column('author', sa.String(length=50), nullable=True))
    op.add_column('books_read', sa.Column('gender', sa.String(length=100), nullable=True))
    op.add_column('books_read', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('books_read', sa.Column('review', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_read', 'review')
    op.drop_column('books_read', 'rating')
    op.drop_column('books_read', 'gender')
    op.drop_column('books_read', 'author')
    # ### end Alembic commands ###
