"""databse upgrade to image upload

Revision ID: 943dfd83d1bd
Revises: 331aa2c03a4c
Create Date: 2026-06-14 23:58:30.243828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943dfd83d1bd'
down_revision: Union[str, Sequence[str], None] = '331aa2c03a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
