"""remove item_id from table books_read

Revision ID: bdd975cfc17d
Revises: 943dfd83d1bd
Create Date: 2026-06-24 21:53:03.049918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd975cfc17d'
down_revision: Union[str, Sequence[str], None] = '943dfd83d1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_read_item_id_fkey'), 'books_read', type_='foreignkey')
    op.drop_column('books_read', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_read', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('books_read_item_id_fkey'), 'books_read', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
